const { errorSchemas } = require("../../commons/schemas/errorSchemas");

const getPurchaseOrderApprovedPonoSchema = {
  tags: ["Item"],
  summary: "API to list items with balance less than or equal to minimum stock and filter by supplier",
  headers: { $ref: "request-headers#" },
  params: {
    type: "object",
    properties: {
      pono: { type: "string" },
      company_id: { type: "integer" }
    },
  },
  response: {
    200: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "integer" },
          pono: { type: "string" },
          podate: { type: "string" },
          supplier_id: { type: "integer" },
          supplier_name: { type: "string" },
          total_items: { type: "number" },
          total_order_qty: { type: "number" },
          sub_total_amt: { type: "number" },
          total_gst_amt: { type: "number" },
          total_cess_amt: { type: "number" },
          grand_total_amt: { type: "number" },
          roff: { type: "number" },
          is_approved: { type: "boolean" },
          is_approved_by: { type: "integer" },
          expiry_date: { type: "string" },
          expired: { type: "boolean" },
          name: { type: "string" },
          short_name: { type: "string" },
          add1: { type: "string" },
          add2: { type: "string" },
          add3: { type: "string" },
          add4: { type: "string" },
          gstin: { type: "string" },
          purchase_order_type: { type: "integer" },
          po_details_lines: {
            type: "array",
            items: {
              type: "object",
              properties: {
                id: { type: "integer" },
                pro_code: { type: "string" },
                pro_name: { type: "string" },
                company_id: { type: "integer" },
                head_id: { type: "integer" },
                typedesign_id: { type: "integer" },
                main_catgory_id: { type: "integer" },
                sub_category_id: { type: "integer" },
                uom_id: { type: "integer" },
                barcode: { type: "string" },
                pur_rate: { type: "number" },
                cost_price: { type: "number" },
                sale_rate: { type: "number" },
                wholesale_rate: { type: "number" },
                mrp: { type: "number" },
                igst: { type: "number" },
                gst: { type: "number" },
                cess: { type: "number" },
                hsn: { type: "string" },
                op_stk: { type: "number" },
                balance: { type: "number" },
                min_stock: { type: "number" },
                allow_neg_stk: { type: "boolean" },
                wscale: { type: "boolean" },
                batch_item: { type: "boolean" },
                discount: { type: "number" },
                short_name: { type: "string" },
                pro_description: { type: "string" },
                unit_name: { type: "string" },
                order_qty: { type: "number" },
                qty: { type: "number" },
                po_qty: { type: "number" },
                po_order_qty: { type: "number" },
                po_loose_qty: { type: "number" },
                soh: { type: "number" },
                expiry_type_id: { type: "integer" },
                expiry_value: { type: "integer" },
                self_life: { type: "integer" },
                case_qty: { type: "number" },
                free_qty: { type: "integer" },
                return_qty: { type: "integer" },
                tray_id: { type: "integer" },
                tray_count: { type: "integer" }
              },
            },
          },
        },

      },
    },
    ...errorSchemas,
  },
};

module.exports = getPurchaseOrderApprovedPonoSchema;
