const OUTLET_PURCHASE_MEMO_MASTER = {
  NAME: "outlet_purchase_memo_master",
  COLUMNS: {
    ID: "id",
    FINANCIAL_YEAR: "financial_year",
    DOCNO: "docno",
    DOCDATE: "docdate",
    SUPPLIER_ID: "supplier_id",
    OUTLET_ID: "outlet_id",
    GRAND_TOTAL_AMT: "grand_total_amt",
    SUB_TOTAL_AMT: "sub_total_amt",
    TOTAL_RETURN_AMT: "total_return_amt",
    INVOICE_NO: "invoice_no",
    INVOICE_DATE: "invoice_date",
    CUSTOMER_TYPE: "customer_type",
    PONO: "pono",
    PODATE: "podate",
    STATUS: "status",
    COMPANY_ID: "company_id",
    TOTAL_ORDER_QTY: "total_order_qty",
    TOTAL_RECEIVED_QTY: "total_received_qty",
    TOTAL_RETURN_QTY: "total_return_qty",
    TOTAL_MEMO_QTY: "total_memo_qty",
    REMARK: "remark",
    RETURN_REMARK: "return_remark",
    RETURN_AMOUNT: "return_amount",
    DISCOUNT: "discount",
    ROFF: "roff",
    OTHER_CHARGES: "other_charges",
    TOTAL_GST_AMT: "total_gst_amt",
    TOTAL_IGST_AMT: "total_igst_amt",
    ADVANCE: "advance",
    TOTAL_CESS_AMT: "total_cess_amt",
    PRODUCT_TYPE: "product_type",
    TCS: "tcs",
    WAREHOUSE_ID: "warehouse_id",
    PURCHASE: "purchase",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    IS_ACTIVE: "is_active",
    IS_GRN_COMPLETE: "is_grn_complete",
    GRN_NO: "grn_no",
    INVOICE_AMOUNT: "invoice_amount",
    IMAGE_URL: "image_url",
    INVOICE_REMARK: "invoice_remark",
    IS_INVOICE_PDF: "is_invoice_pdf",
    CLEAR_INVOICE_USER: "clear_invoice_user",
    UPLOAD_INVOICE_USER: "upload_invoice_user"

  }
};

const OUTLET_PURCHASE_MEMO_DETAILS = {
  NAME: "outlet_purchase_memo_details",
  COLUMNS: {
    ID: "id",
    OUTLET_PURCHASE_MEMO_MST_ID: "outlet_purchase_memo_mst_id",
    FINANCIAL_YEAR: "financial_year",
    DOCNO: "docno",
    DOCDATE: "docdate",
    COMPANY_ID: "company_id",
    SUPPLIER_ID: "supplier_id",
    OUTLET_ID: "outlet_id",
    WAREHOUSE_ID: "warehouse_id",
    PO_NO: "po_no",
    PROD_ID: "prod_id",
    PROD_CODE: "prod_code",
    HSN_CODE: "hsn_code",
    CAT_ID: "cat_id",
    SUB_CAT_ID: "sub_cat_id",
    HEAD_ID: "head_id",
    TYPE_DESIGN_ID: "type_design_id",
    UOM_ID: "uom_id",
    BARCODE: "barcode",
    ORDER_QTY: "order_qty",
    RECIVED_QTY: "recived_qty",
    RETURN_QTY: "return_qty",
    QTY: "qty",
    FREE_QTY: "free_qty",
    DISCOUNT: "discount",
    DISCOUNT_AMOUNT: "discount_amount",
    PURCHASE_RATE: "purchase_rate",
    AMOUNT: "amount",
    RETURN_AMOUNT: "return_amount",
    ACCEPTED_MARGIN: "accepted_margin",
    MRP: "mrp",
    PO_MRP: "po_mrp",
    SALE_RATE: "sale_rate",
    GST: "gst",
    GST_AMOUNT: "gst_amount",
    IGST: "igst",
    IGST_AMOUNT: "igst_amount",
    CGST: "cgst",
    SGST: "sgst",
    CESS: "cess",
    CESS_AMOUNT: "cess_amount",
    PACK_FLAG: "pack_flag",
    PACK_QTY: "pack_qty",
    SELF_LIFE_EXPIRY_DAYS: "self_life_expiry_days",
    RETURN_QTY: "return_qty",
    PURCHASE: "purchase",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    IS_ACTIVE: "is_active",
    TEMP_REC_QTY: "temp_rec_qty",
    TEMP_GRN_RETURN_QTY: "temp_grn_return_qty",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    EXP_PERIOD: "exp_period",
    MANF_DATE: "manf_date",
    EXP_DATE: "exp_date",
    BATCH_NO: "batch_no",
    TYPE_ID: "type_id",
    IS_GRN_COMPLETE: "is_grn_complete",
    RECEIVED_GRN_QTY: "received_grn_qty"
  }
};

const OUTLET_PURCHASE_MEMO_BATCH_DETAILS = {
  NAME: "outlet_purchase_memo_batch_details",
  COLUMNS: {
    ID: "id",
    OUTLET_PO_MEMO_MST_ID: "outlet_po_memo_mst_id",
    PRODUCT_ID: "product_id",
    PRODUCT_CODE: "product_code",
    BATCH_NO: "batch_no",
    QTY: "qty",
    MRP: "mrp",
    SELF_LIFE_EXPIRY_DAYS: "self_life_expiry_days",
    RETURN_QTY: "return_qty",
    COMPANY_ID: "company_id",
    MANUFACTURE_DATE: "manufacture_date",
    EXPIRY_ID: "expiry_id",
    EXPIRY_VALUE: "expiry_value",
    EXPIRY_DATE: "expiry_date"
  }
};

const OUTLET_PURCHASE_MEMO_MASTER_TEMP = {
  NAME: "outlet_purchase_memo_master_temp",
  COLUMNS: {
    ID: "id",
    DOCNO: "docno",
    DOCDATE: "docdate",
    PONO: "pono",
    SUPPLIER_ID: "supplier_id",
    OUTLET_ID: "outlet_id",
    COMPANY_ID: "company_id",
    WAREHOUSE_ID: "warehouse_id",
    INVOICE_NO: "invoice_no",
    INVOICE_DATE: "invoice_date",
    INVOICE_AMOUNT: "invoice_amount",
    IMAGE_URL: "image_url",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    IS_ACTIVE: "is_active"
  }
};

const OUTLET_PURCHASE_MEMO_DETAILS_TEMP = {
  NAME: "outlet_purchase_memo_details_temp",
  COLUMNS: {
    ID: "id",
    OP_MEMO_MST_TEMP_ID: "op_memo_mst_temp_id",
    DOCNO: "docno",
    DOCDATE: "docdate",
    COMPANY_ID: "company_id",
    SUPPLIER_ID: "supplier_id",
    OUTLET_ID: "outlet_id",
    WAREHOUSE_ID: "warehouse_id",
    PO_NO: "po_no",
    PROD_ID: "prod_id",
    PROD_CODE: "prod_code",
    UOM_ID: "uom_id",
    PO_QTY: "po_qty",
    MEMO_QTY: "memo_qty",
    MEMO_RETURN_QTY: "memo_return_qty",
    MEMO_FREE_QTY: "memo_free_qty",
    MEMO_TOTAL_QTY: "memo_total_qty",
    MEMO_MRP: "memo_mrp",
    PO_MRP: "po_mrp",
    IS_ACTIVE: "is_active",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    EXP_PERIOD: "exp_period",
    TYPE_ID: "type_id"
  }
};

const OUTLET_PURCHASE_MEMO_BATCH_DETAILS_TEMP = {
  NAME: "outlet_purchase_memo_batch_details_temp",
  COLUMNS: {
    ID: "id",
    OP_MEMO_MST_TEMP_ID: "op_memo_mst_temp_id",
    PRODUCT_ID: "product_id",
    PRODUCT_CODE: "product_code",
    BATCH_NO: "batch_no",
    MEMO_QTY: "memo_qty",
    MEMO_MRP: "memo_mrp",
    SELF_LIFE_EXPIRY_DAYS: "self_life_expiry_days",
    MEMO_RETURN_QTY: "memo_return_qty",
    COMPANY_ID: "company_id",
    MANUFACTURE_DATE: "manufacture_date",
    EXPIRY_ID: "expiry_id",
    EXPIRY_VALUE: "expiry_value",
    EXPIRY_DATE: "expiry_date"
  }
};


module.exports = {
  OUTLET_PURCHASE_MEMO_MASTER,
  OUTLET_PURCHASE_MEMO_DETAILS,
  OUTLET_PURCHASE_MEMO_BATCH_DETAILS
};
