const { errorSchemas } = require("../../../commons/schemas/errorSchemas");

const getAllPurchase = {
  tags: ["Item INFO"],
  summary: "This API is to get Item Info",
  headers: { $ref: "request-headers#" },
  response: {
    200: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "integer" },
          docno: { type: "string" },
          docdate: { type: "string", format: "date-time" },
          partycode: { type: "integer" },
          amount: { type: "string" },
          gst_per: { type: "string" },
          gst_amt: { type: "string" },
          cess_per: { type: "string" },
          cess_amt: { type: "string" },
          roff: { type: "string" },
          freight_charges: { type: "string" },
          other_charges: { type: "string" },
          podate: { type: ["string", "null"], format: "date-time" },
          partydc: { type: "string" },
          outstanding: { type: "string" },
          partydcdate: { type: "string", format: "date-time" },
          company_id: { type: "integer" },
          is_active: { type: "boolean" },
          created_at: { type: "string", format: "date-time" },
          updated_at: { type: "string", format: "date-time" },
          created_by: { type: "integer" },
          updated_by: { type: "integer" },
          is_barcode_generated: { type: "integer" },
          name: { type: "string" },
          short_name: { type: "string" },
          mobile: { type: "string" },
          phone: { type: "string" },
          add1: { type: "string" },
          add2: { type: "string" },
          add3: { type: "string" },
          add4: { type: "string" },
          city: { type: "integer" },
          pincode: { type: "string" },
          state: { type: "integer" },
          email: { type: "string", format: "email" },
          website: { type: "string" },
          op_bal: { type: "string" },
          balance: { type: "string" },
          custtype: { type: "string" },
          bank_ac_no: { type: "string" },
          bankname: { type: "string" },
          ac_name: { type: "string" },
          ifsccode: { type: "string" },
          gstin: { type: "string" },
          country: { type: "integer" },
          fssaino: { type: "string" },
        },
      },
    },
    ...errorSchemas,
  },
};

module.exports = getAllPurchase;

